//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTransportApp.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sections
    {
        public int SectionID { get; set; }
        public double Start_Longitude { get; set; }
        public double Start_Latitude { get; set; }
        public double End_Longitude { get; set; }
        public double End_Latitude { get; set; }
        public int Order { get; set; }
        public Nullable<int> Route_RouteID { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
